//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.ArcGIS.ExceptionHandler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRI.ArcGIS.ExceptionHandler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_COPY {
            get {
                object obj = ResourceManager.GetObject("BITMAP_COPY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_MESSAGE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_MESSAGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_NEW {
            get {
                object obj = ResourceManager.GetObject("BITMAP_NEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_PAUSE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_PAUSE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_PLAY {
            get {
                object obj = ResourceManager.GetObject("BITMAP_PLAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_PRINT {
            get {
                object obj = ResourceManager.GetObject("BITMAP_PRINT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_PRINT_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("BITMAP_PRINT_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_PRINT_SETUP {
            get {
                object obj = ResourceManager.GetObject("BITMAP_PRINT_SETUP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_SAVE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_SAVE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;html&quot; doctype-public=&quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; doctype-system=&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot; /&gt;
        ///  &lt;xsl:param name=&quot;title&quot; select=&quot;title&quot; /&gt;
        ///  &lt;xsl:param name=&quot;environment&quot; select=&quot;environment&quot; /&gt;
        ///  &lt;xsl:param name=&quot;os&quot; select=&quot;os&quot; /&gt;
        ///  &lt;xsl:param name=&quot;osvalue&quot; select=&quot;osvalue&quot; /&gt;
        ///  &lt;xsl:param name=&quot;clr&quot; select=&quot;clr&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_HTMLREPORT {
            get {
                return ResourceManager.GetString("FILE_HTMLREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        internal static string HTML_ASSEMBLY {
            get {
                return ResourceManager.GetString("HTML_ASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR.
        /// </summary>
        internal static string HTML_CLR {
            get {
                return ResourceManager.GetString("HTML_CLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string HTML_DATE {
            get {
                return ResourceManager.GetString("HTML_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string HTML_ENVIRONMENT {
            get {
                return ResourceManager.GetString("HTML_ENVIRONMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions.
        /// </summary>
        internal static string HTML_EXCEPTIONS {
            get {
                return ResourceManager.GetString("HTML_EXCEPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string HTML_MESSAGE {
            get {
                return ResourceManager.GetString("HTML_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS.
        /// </summary>
        internal static string HTML_OS {
            get {
                return ResourceManager.GetString("HTML_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack.
        /// </summary>
        internal static string HTML_STACK {
            get {
                return ResourceManager.GetString("HTML_STACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Report.
        /// </summary>
        internal static string HTML_TITLE {
            get {
                return ResourceManager.GetString("HTML_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESRI Exception Handler.
        /// </summary>
        internal static string TEXT_EXCEPTION_HANDLER {
            get {
                return ResourceManager.GetString("TEXT_EXCEPTION_HANDLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TEXT_EXIT {
            get {
                return ResourceManager.GetString("TEXT_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string TEXT_FILE {
            get {
                return ResourceManager.GetString("TEXT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string TEXT_READY {
            get {
                return ResourceManager.GetString("TEXT_READY", resourceCulture);
            }
        }
    }
}
