//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.ArcGIS.ArcDiagrammer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRI.ArcGIS.ArcDiagrammer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ALIGN_BOTTOM {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ALIGN_BOTTOM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ALIGN_CENTER {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ALIGN_CENTER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ALIGN_LEFT {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ALIGN_LEFT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ALIGN_MIDDLE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ALIGN_MIDDLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ALIGN_RIGHT {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ALIGN_RIGHT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ALIGN_TOP {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ALIGN_TOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_BLACK {
            get {
                object obj = ResourceManager.GetObject("BITMAP_BLACK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_BLUE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_BLUE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_CLOSE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_CLOSE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_COPY {
            get {
                object obj = ResourceManager.GetObject("BITMAP_COPY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_CUT {
            get {
                object obj = ResourceManager.GetObject("BITMAP_CUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_DATA_REPORT {
            get {
                object obj = ResourceManager.GetObject("BITMAP_DATA_REPORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_DELETE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_DELETE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ERROR {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ERROR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ESRI {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ESRI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ESRI_LOGO {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ESRI_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_EXPORT {
            get {
                object obj = ResourceManager.GetObject("BITMAP_EXPORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_HELP {
            get {
                object obj = ResourceManager.GetObject("BITMAP_HELP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_LAYOUT_CIRCULAR {
            get {
                object obj = ResourceManager.GetObject("BITMAP_LAYOUT_CIRCULAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_LAYOUT_FORCEDDIRECT {
            get {
                object obj = ResourceManager.GetObject("BITMAP_LAYOUT_FORCEDDIRECT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_LAYOUT_HIERACHICAL {
            get {
                object obj = ResourceManager.GetObject("BITMAP_LAYOUT_HIERACHICAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_LAYOUT_ORTHOGONAL {
            get {
                object obj = ResourceManager.GetObject("BITMAP_LAYOUT_ORTHOGONAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_LAYOUT_TREE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_LAYOUT_TREE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_MAIL {
            get {
                object obj = ResourceManager.GetObject("BITMAP_MAIL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_MESSAGES {
            get {
                object obj = ResourceManager.GetObject("BITMAP_MESSAGES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_METADATA {
            get {
                object obj = ResourceManager.GetObject("BITMAP_METADATA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_MODE_LINK {
            get {
                object obj = ResourceManager.GetObject("BITMAP_MODE_LINK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_MODE_NORMAL {
            get {
                object obj = ResourceManager.GetObject("BITMAP_MODE_NORMAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_NEW {
            get {
                object obj = ResourceManager.GetObject("BITMAP_NEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_OK {
            get {
                object obj = ResourceManager.GetObject("BITMAP_OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_OPEN {
            get {
                object obj = ResourceManager.GetObject("BITMAP_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_OPTIONS {
            get {
                object obj = ResourceManager.GetObject("BITMAP_OPTIONS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_PASTE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_PASTE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_PRINT {
            get {
                object obj = ResourceManager.GetObject("BITMAP_PRINT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_PRINT_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("BITMAP_PRINT_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_PRINT_SETUP {
            get {
                object obj = ResourceManager.GetObject("BITMAP_PRINT_SETUP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_PUBLISH {
            get {
                object obj = ResourceManager.GetObject("BITMAP_PUBLISH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_REDO {
            get {
                object obj = ResourceManager.GetObject("BITMAP_REDO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_SAVE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_SAVE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_SAVEAS {
            get {
                object obj = ResourceManager.GetObject("BITMAP_SAVEAS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_SCHEMA_REPORT {
            get {
                object obj = ResourceManager.GetObject("BITMAP_SCHEMA_REPORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_SELECT_ALL {
            get {
                object obj = ResourceManager.GetObject("BITMAP_SELECT_ALL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_SILVER {
            get {
                object obj = ResourceManager.GetObject("BITMAP_SILVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_SPLIT_HORIZONTAL {
            get {
                object obj = ResourceManager.GetObject("BITMAP_SPLIT_HORIZONTAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_SPLIT_VERTICAL {
            get {
                object obj = ResourceManager.GetObject("BITMAP_SPLIT_VERTICAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_UNDO {
            get {
                object obj = ResourceManager.GetObject("BITMAP_UNDO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_VALIDATE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_VALIDATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_WARNING {
            get {
                object obj = ResourceManager.GetObject("BITMAP_WARNING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_XML_REPORT {
            get {
                object obj = ResourceManager.GetObject("BITMAP_XML_REPORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ZOOM_IN {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ZOOM_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ZOOM_OUT {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ZOOM_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ZOOM_TO_ACTUAL_SIZE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ZOOM_TO_ACTUAL_SIZE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ZOOM_TO_SELECTION {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ZOOM_TO_SELECTION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ZOOM_TO_WINDOW {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ZOOM_TO_WINDOW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon DIAGRAMMER {
            get {
                object obj = ResourceManager.GetObject("DIAGRAMMER", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;x:stylesheet xmlns:x=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;
        ///              xmlns:dt=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///              xmlns:d2=&quot;urn:schemas-microsoft-com:datatypes&quot;&gt;
        ///  &lt;x:output method=&quot;html&quot;/&gt;
        ///  &lt;x:template match=&quot;/&quot;&gt;
        ///    &lt;HTML&gt;
        ///      &lt;HEAD&gt;
        ///        &lt;STYLE&gt;
        ///          &lt;![CDATA[
        ///    BODY{font:x-small &apos;Verdana&apos;;margin-right:1.5em} 
        ///    .c{cursor:hand} 
        ///    .b{color:red;font-family:&apos;Courier New&apos;;font-weight:bold;text-decoration:none} 
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_DEFAULT {
            get {
                return ResourceManager.GetString("FILE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/TR/WD-xsl&quot; TYPE=&quot;text/javascript&quot;&gt;
        ///
        ///&lt;!-- An xsl template for displaying ISO and ESRI metadata in ArcCatalog 
        ///     with similar look to traditional FGDC.
        ///     Shows all elements in ISO standard and ESRI profile, and indicates
        ///     which elements have been automatically updated by ArcCatalog.
        ///
        ///     Copyright (c) 2001-2008, Environmental Systems Research Institute, Inc. All rights reserved.
        ///	
        ///     Revision History: C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ISO {
            get {
                return ResourceManager.GetString("ISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;100%.
        /// </summary>
        internal static string TEXT_100_PERCENT_ {
            get {
                return ResourceManager.GetString("TEXT_100_PERCENT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;200%.
        /// </summary>
        internal static string TEXT_200_PERCENT_ {
            get {
                return ResourceManager.GetString("TEXT_200_PERCENT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25%.
        /// </summary>
        internal static string TEXT_25_PERCENT_ {
            get {
                return ResourceManager.GetString("TEXT_25_PERCENT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;300%.
        /// </summary>
        internal static string TEXT_300_PERCENT_ {
            get {
                return ResourceManager.GetString("TEXT_300_PERCENT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;50%.
        /// </summary>
        internal static string TEXT_50_PERCENT_ {
            get {
                return ResourceManager.GetString("TEXT_50_PERCENT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;75%.
        /// </summary>
        internal static string TEXT_75_PERCENT_ {
            get {
                return ResourceManager.GetString("TEXT_75_PERCENT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ArcGIS Diagrammer.
        /// </summary>
        internal static string TEXT_ABOUT_ARCDIAGRAMMER {
            get {
                return ResourceManager.GetString("TEXT_ABOUT_ARCDIAGRAMMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About ArcGIS Diagrammer.
        /// </summary>
        internal static string TEXT_ABOUT_ARCDIAGRAMMER_ {
            get {
                return ResourceManager.GetString("TEXT_ABOUT_ARCDIAGRAMMER_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string TEXT_ACTIVATE {
            get {
                return ResourceManager.GetString("TEXT_ACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subtype.
        /// </summary>
        internal static string TEXT_ADD_SUBTYPE {
            get {
                return ResourceManager.GetString("TEXT_ADD_SUBTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;Bottom.
        /// </summary>
        internal static string TEXT_ALIGN_BOTTOM_ {
            get {
                return ResourceManager.GetString("TEXT_ALIGN_BOTTOM_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;Center.
        /// </summary>
        internal static string TEXT_ALIGN_CENTER_ {
            get {
                return ResourceManager.GetString("TEXT_ALIGN_CENTER_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;Left.
        /// </summary>
        internal static string TEXT_ALIGN_LEFT_ {
            get {
                return ResourceManager.GetString("TEXT_ALIGN_LEFT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;Middle.
        /// </summary>
        internal static string TEXT_ALIGN_MIDDLE_ {
            get {
                return ResourceManager.GetString("TEXT_ALIGN_MIDDLE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;Right.
        /// </summary>
        internal static string TEXT_ALIGN_RIGHT_ {
            get {
                return ResourceManager.GetString("TEXT_ALIGN_RIGHT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align &amp;Top.
        /// </summary>
        internal static string TEXT_ALIGN_TOP_ {
            get {
                return ResourceManager.GetString("TEXT_ALIGN_TOP_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Diagrammer Documents.
        /// </summary>
        internal static string TEXT_ALL_DIAGRAMMER_DOCUMENTS {
            get {
                return ResourceManager.GetString("TEXT_ALL_DIAGRAMMER_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string TEXT_ALL_FILES {
            get {
                return ResourceManager.GetString("TEXT_ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string TEXT_APPLY {
            get {
                return ResourceManager.GetString("TEXT_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Diagrammer.
        /// </summary>
        internal static string TEXT_ARCDIAGRAMMER {
            get {
                return ResourceManager.GetString("TEXT_ARCDIAGRAMMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagrammer Documents.
        /// </summary>
        internal static string TEXT_ARCGIS_DIAGRAMMER_DOCUMENT {
            get {
                return ResourceManager.GetString("TEXT_ARCGIS_DIAGRAMMER_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Diagrammer &amp;User Guide.
        /// </summary>
        internal static string TEXT_ARCGIS_DIAGRAMMER_USERGUIDE_ {
            get {
                return ResourceManager.GetString("TEXT_ARCGIS_DIAGRAMMER_USERGUIDE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;ArcGIS Ideas.
        /// </summary>
        internal static string TEXT_ARCGIS_IDEAS_ {
            get {
                return ResourceManager.GetString("TEXT_ARCGIS_IDEAS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portions of this work are:|Copyright © 2008 Divelements Limited. All rights reserved.|Copyright © 2008 Crainiate Software. All rights reserved..
        /// </summary>
        internal static string TEXT_ATTRIBUTION_STATEMENT {
            get {
                return ResourceManager.GetString("TEXT_ATTRIBUTION_STATEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;uto Hide All.
        /// </summary>
        internal static string TEXT_AUTO_HIDE_ALL_ {
            get {
                return ResourceManager.GetString("TEXT_AUTO_HIDE_ALL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Black.
        /// </summary>
        internal static string TEXT_BLACK_ {
            get {
                return ResourceManager.GetString("TEXT_BLACK_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B&amp;lue.
        /// </summary>
        internal static string TEXT_BLUE_ {
            get {
                return ResourceManager.GetString("TEXT_BLUE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TEXT_CANCEL {
            get {
                return ResourceManager.GetString("TEXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string TEXT_CATALOG {
            get {
                return ResourceManager.GetString("TEXT_CATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Catalog.
        /// </summary>
        internal static string TEXT_CATALOG_ {
            get {
                return ResourceManager.GetString("TEXT_CATALOG_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular.
        /// </summary>
        internal static string TEXT_CIRCULAR {
            get {
                return ResourceManager.GetString("TEXT_CIRCULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Circular.
        /// </summary>
        internal static string TEXT_CIRCULAR_ {
            get {
                return ResourceManager.GetString("TEXT_CIRCULAR_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string TEXT_CLOSE {
            get {
                return ResourceManager.GetString("TEXT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string TEXT_CLOSE_ {
            get {
                return ResourceManager.GetString("TEXT_CLOSE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close &amp;All Documents.
        /// </summary>
        internal static string TEXT_CLOSE_ALL_DOCUMENTS_ {
            get {
                return ResourceManager.GetString("TEXT_CLOSE_ALL_DOCUMENTS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close the current diagram without saving?.
        /// </summary>
        internal static string TEXT_CLOSE_WITHOUT_SAVING {
            get {
                return ResourceManager.GetString("TEXT_CLOSE_WITHOUT_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Color Scheme.
        /// </summary>
        internal static string TEXT_COLOR_SCHEME_ {
            get {
                return ResourceManager.GetString("TEXT_COLOR_SCHEME_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string TEXT_COMMANDS {
            get {
                return ResourceManager.GetString("TEXT_COMMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Author.
        /// </summary>
        internal static string TEXT_CONTACT_AUTHOR {
            get {
                return ResourceManager.GetString("TEXT_CONTACT_AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string TEXT_COPY_ {
            get {
                return ResourceManager.GetString("TEXT_COPY_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2008 ESRI Inc. All rights reserved..
        /// </summary>
        internal static string TEXT_COPYRIGHT_STATEMENT {
            get {
                return ResourceManager.GetString("TEXT_COPYRIGHT_STATEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp;Data Report.
        /// </summary>
        internal static string TEXT_CREATE_DATA_REPORT_ {
            get {
                return ResourceManager.GetString("TEXT_CREATE_DATA_REPORT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create One to Many Relationship.
        /// </summary>
        internal static string TEXT_CREATE_ONE_TO_MANY_RELATIONSHIP {
            get {
                return ResourceManager.GetString("TEXT_CREATE_ONE_TO_MANY_RELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create Schema Report.
        /// </summary>
        internal static string TEXT_CREATE_SCHEMA_REPORT_ {
            get {
                return ResourceManager.GetString("TEXT_CREATE_SCHEMA_REPORT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ut.
        /// </summary>
        internal static string TEXT_CUT_ {
            get {
                return ResourceManager.GetString("TEXT_CUT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string TEXT_DATA {
            get {
                return ResourceManager.GetString("TEXT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Report.
        /// </summary>
        internal static string TEXT_DATA_REPORT {
            get {
                return ResourceManager.GetString("TEXT_DATA_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Data Report.
        /// </summary>
        internal static string TEXT_DATA_REPORT_ {
            get {
                return ResourceManager.GetString("TEXT_DATA_REPORT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Default).
        /// </summary>
        internal static string TEXT_DEFAUL_BR {
            get {
                return ResourceManager.GetString("TEXT_DEFAUL_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string TEXT_DEFAULT {
            get {
                return ResourceManager.GetString("TEXT_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Default.
        /// </summary>
        internal static string TEXT_DEFAULT_ {
            get {
                return ResourceManager.GetString("TEXT_DEFAULT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string TEXT_DELETE_ {
            get {
                return ResourceManager.GetString("TEXT_DELETE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TEXT_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by the Applications Prototype Lab, ESRI Redlands.
        /// </summary>
        internal static string TEXT_DEVELOPED_BY_STATEMENT {
            get {
                return ResourceManager.GetString("TEXT_DEVELOPED_BY_STATEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        internal static string TEXT_DIAGRAM {
            get {
                return ResourceManager.GetString("TEXT_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Colors.
        /// </summary>
        internal static string TEXT_DIAGRAM_COLORS {
            get {
                return ResourceManager.GetString("TEXT_DIAGRAM_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Discussion Forum.
        /// </summary>
        internal static string TEXT_DISCUSSION_FORUM_ {
            get {
                return ResourceManager.GetString("TEXT_DISCUSSION_FORUM_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc&amp;kable.
        /// </summary>
        internal static string TEXT_DOCKABLE_ {
            get {
                return ResourceManager.GetString("TEXT_DOCKABLE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string TEXT_DOMAIN {
            get {
                return ResourceManager.GetString("TEXT_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Domain View.
        /// </summary>
        internal static string TEXT_DOMAIN_VIEW_ {
            get {
                return ResourceManager.GetString("TEXT_DOMAIN_VIEW_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string TEXT_EDIT_ {
            get {
                return ResourceManager.GetString("TEXT_EDIT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string TEXT_EMPTY {
            get {
                return ResourceManager.GetString("TEXT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error List.
        /// </summary>
        internal static string TEXT_ERROR_LIST {
            get {
                return ResourceManager.GetString("TEXT_ERROR_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Error List.
        /// </summary>
        internal static string TEXT_ERROR_LIST_ {
            get {
                return ResourceManager.GetString("TEXT_ERROR_LIST_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESRI &amp;Home.
        /// </summary>
        internal static string TEXT_ESRI_HOME_ {
            get {
                return ResourceManager.GetString("TEXT_ESRI_HOME_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exceptions.
        /// </summary>
        internal static string TEXT_EXCEPTIONS_ {
            get {
                return ResourceManager.GetString("TEXT_EXCEPTIONS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string TEXT_EXIT_ {
            get {
                return ResourceManager.GetString("TEXT_EXIT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export....
        /// </summary>
        internal static string TEXT_EXPORT_ {
            get {
                return ResourceManager.GetString("TEXT_EXPORT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Diagram.
        /// </summary>
        internal static string TEXT_EXPORT_DIAGRAM {
            get {
                return ResourceManager.GetString("TEXT_EXPORT_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Class.
        /// </summary>
        internal static string TEXT_FEATURE_CLASS {
            get {
                return ResourceManager.GetString("TEXT_FEATURE_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string TEXT_FILE_ {
            get {
                return ResourceManager.GetString("TEXT_FILE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File Geodatabase.
        /// </summary>
        internal static string TEXT_FILE_GEODATABASE_ {
            get {
                return ResourceManager.GetString("TEXT_FILE_GEODATABASE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Floating.
        /// </summary>
        internal static string TEXT_FLOATING_ {
            get {
                return ResourceManager.GetString("TEXT_FLOATING_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced Direct.
        /// </summary>
        internal static string TEXT_FORCED_DIRECT {
            get {
                return ResourceManager.GetString("TEXT_FORCED_DIRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Forced Direct.
        /// </summary>
        internal static string TEXT_FORCED_DIRECT_ {
            get {
                return ResourceManager.GetString("TEXT_FORCED_DIRECT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string TEXT_FULL {
            get {
                return ResourceManager.GetString("TEXT_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Full.
        /// </summary>
        internal static string TEXT_FULL_ {
            get {
                return ResourceManager.GetString("TEXT_FULL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodatabase Objects.
        /// </summary>
        internal static string TEXT_GEODATABASE_OBJECTS {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string TEXT_HELP_ {
            get {
                return ResourceManager.GetString("TEXT_HELP_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide.
        /// </summary>
        internal static string TEXT_HIDE_ {
            get {
                return ResourceManager.GetString("TEXT_HIDE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchical.
        /// </summary>
        internal static string TEXT_HIERARCHICAL {
            get {
                return ResourceManager.GetString("TEXT_HIERARCHICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hierarchical.
        /// </summary>
        internal static string TEXT_HIERARCHICAL_ {
            get {
                return ResourceManager.GetString("TEXT_HIERARCHICAL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi&amp;story.
        /// </summary>
        internal static string TEXT_HISTORY_ {
            get {
                return ResourceManager.GetString("TEXT_HISTORY_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Mode.
        /// </summary>
        internal static string TEXT_INTERACTIVE_MODE {
            get {
                return ResourceManager.GetString("TEXT_INTERACTIVE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Interactive Mode.
        /// </summary>
        internal static string TEXT_INTERACTIVE_MODE_ {
            get {
                return ResourceManager.GetString("TEXT_INTERACTIVE_MODE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string TEXT_LAYOUT {
            get {
                return ResourceManager.GetString("TEXT_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Layout.
        /// </summary>
        internal static string TEXT_LAYOUT_ {
            get {
                return ResourceManager.GetString("TEXT_LAYOUT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Link Mode.
        /// </summary>
        internal static string TEXT_LINK_MODE_ {
            get {
                return ResourceManager.GetString("TEXT_LINK_MODE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string TEXT_MAIN_MENU {
            get {
                return ResourceManager.GetString("TEXT_MAIN_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string TEXT_MESSAGES {
            get {
                return ResourceManager.GetString("TEXT_MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Messages.
        /// </summary>
        internal static string TEXT_MESSAGES_ {
            get {
                return ResourceManager.GetString("TEXT_MESSAGES_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        internal static string TEXT_METADATA {
            get {
                return ResourceManager.GetString("TEXT_METADATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Metadata.
        /// </summary>
        internal static string TEXT_METADATA_ {
            get {
                return ResourceManager.GetString("TEXT_METADATA_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TEXT_NAME {
            get {
                return ResourceManager.GetString("TEXT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string TEXT_NAVIGATION {
            get {
                return ResourceManager.GetString("TEXT_NAVIGATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Navigation.
        /// </summary>
        internal static string TEXT_NAVIGATION_ {
            get {
                return ResourceManager.GetString("TEXT_NAVIGATION_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string TEXT_NEW_ {
            get {
                return ResourceManager.GetString("TEXT_NEW_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Hori&amp;zontal Tab Group.
        /// </summary>
        internal static string TEXT_NEW_HORIZONTAL_TAB_GROUP_ {
            get {
                return ResourceManager.GetString("TEXT_NEW_HORIZONTAL_TAB_GROUP_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New &amp;Vertical Tab Group.
        /// </summary>
        internal static string TEXT_NEW_VERTICAL_TAB_GROUP_ {
            get {
                return ResourceManager.GetString("TEXT_NEW_VERTICAL_TAB_GROUP_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string TEXT_NONE_BR {
            get {
                return ResourceManager.GetString("TEXT_NONE_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Normal Mode.
        /// </summary>
        internal static string TEXT_NORMAL_MODE_ {
            get {
                return ResourceManager.GetString("TEXT_NORMAL_MODE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not Available).
        /// </summary>
        internal static string TEXT_NOT_AVAILABLE_BR {
            get {
                return ResourceManager.GetString("TEXT_NOT_AVAILABLE_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TEXT_OK {
            get {
                return ResourceManager.GetString("TEXT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open....
        /// </summary>
        internal static string TEXT_OPEN_ {
            get {
                return ResourceManager.GetString("TEXT_OPEN_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open XML Workspace Document.
        /// </summary>
        internal static string TEXT_OPEN_XML_WORKSPACE_DOCUMENT {
            get {
                return ResourceManager.GetString("TEXT_OPEN_XML_WORKSPACE_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string TEXT_OPTIONS {
            get {
                return ResourceManager.GetString("TEXT_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options....
        /// </summary>
        internal static string TEXT_OPTIONS_ {
            get {
                return ResourceManager.GetString("TEXT_OPTIONS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orthogonal.
        /// </summary>
        internal static string TEXT_ORTHOGONAL {
            get {
                return ResourceManager.GetString("TEXT_ORTHOGONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Orthogonal.
        /// </summary>
        internal static string TEXT_ORTHOGONAL_ {
            get {
                return ResourceManager.GetString("TEXT_ORTHOGONAL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string TEXT_OVERVIEW {
            get {
                return ResourceManager.GetString("TEXT_OVERVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Overview.
        /// </summary>
        internal static string TEXT_OVERVIEW_ {
            get {
                return ResourceManager.GetString("TEXT_OVERVIEW_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Page.
        /// </summary>
        internal static string TEXT_PAGE_ {
            get {
                return ResourceManager.GetString("TEXT_PAGE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette.
        /// </summary>
        internal static string TEXT_PALETTE {
            get {
                return ResourceManager.GetString("TEXT_PALETTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Palette.
        /// </summary>
        internal static string TEXT_PALETTE_ {
            get {
                return ResourceManager.GetString("TEXT_PALETTE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        internal static string TEXT_PASTE_ {
            get {
                return ResourceManager.GetString("TEXT_PASTE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string TEXT_PATH {
            get {
                return ResourceManager.GetString("TEXT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Personal Geodatabase.
        /// </summary>
        internal static string TEXT_PERSONAL_GEODATABASE_ {
            get {
                return ResourceManager.GetString("TEXT_PERSONAL_GEODATABASE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print....
        /// </summary>
        internal static string TEXT_PRINT_ {
            get {
                return ResourceManager.GetString("TEXT_PRINT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pre&amp;view....
        /// </summary>
        internal static string TEXT_PRINT_PREVIEW_ {
            get {
                return ResourceManager.GetString("TEXT_PRINT_PREVIEW_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Set&amp;up....
        /// </summary>
        internal static string TEXT_PRINT_SETUP_ {
            get {
                return ResourceManager.GetString("TEXT_PRINT_SETUP_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Setup.
        /// </summary>
        internal static string TEXT_PRINTER_SETUP {
            get {
                return ResourceManager.GetString("TEXT_PRINTER_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string TEXT_PROPERTIES {
            get {
                return ResourceManager.GetString("TEXT_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;roperties.
        /// </summary>
        internal static string TEXT_PROPERTIES_ {
            get {
                return ResourceManager.GetString("TEXT_PROPERTIES_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;ublish....
        /// </summary>
        internal static string TEXT_PUBLISH_ {
            get {
                return ResourceManager.GetString("TEXT_PUBLISH_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string TEXT_READY {
            get {
                return ResourceManager.GetString("TEXT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string TEXT_REDO_ {
            get {
                return ResourceManager.GetString("TEXT_REDO_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Renderer.
        /// </summary>
        internal static string TEXT_RENDERER_ {
            get {
                return ResourceManager.GetString("TEXT_RENDERER_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reorder Fields.
        /// </summary>
        internal static string TEXT_REORDER_FIELDS_ {
            get {
                return ResourceManager.GetString("TEXT_REORDER_FIELDS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string TEXT_REPORT {
            get {
                return ResourceManager.GetString("TEXT_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Validate.
        /// </summary>
        internal static string TEXT_REPORTER_ {
            get {
                return ResourceManager.GetString("TEXT_REPORTER_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string TEXT_RESET {
            get {
                return ResourceManager.GetString("TEXT_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        internal static string TEXT_RESET_ {
            get {
                return ResourceManager.GetString("TEXT_RESET_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        internal static string TEXT_RESET_ALL {
            get {
                return ResourceManager.GetString("TEXT_RESET_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets All Tabs.
        /// </summary>
        internal static string TEXT_RESET_ALL_TABS {
            get {
                return ResourceManager.GetString("TEXT_RESET_ALL_TABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset all tabs?.
        /// </summary>
        internal static string TEXT_RESET_ALL_TABS_WARNING {
            get {
                return ResourceManager.GetString("TEXT_RESET_ALL_TABS_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets Current Tab.
        /// </summary>
        internal static string TEXT_RESET_CURRENT_TAB {
            get {
                return ResourceManager.GetString("TEXT_RESET_CURRENT_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset the current tab?.
        /// </summary>
        internal static string TEXT_RESET_CURRENT_TAB_WARNING {
            get {
                return ResourceManager.GetString("TEXT_RESET_CURRENT_TAB_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restore Tab Group.
        /// </summary>
        internal static string TEXT_RESTORE_TAB_GROUP_ {
            get {
                return ResourceManager.GetString("TEXT_RESTORE_TAB_GROUP_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string TEXT_SAVE {
            get {
                return ResourceManager.GetString("TEXT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save {0}.
        /// </summary>
        internal static string TEXT_SAVE_ {
            get {
                return ResourceManager.GetString("TEXT_SAVE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} &amp;As....
        /// </summary>
        internal static string TEXT_SAVE_AS_ {
            get {
                return ResourceManager.GetString("TEXT_SAVE_AS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Diagram.
        /// </summary>
        internal static string TEXT_SAVE_DIAGRAM {
            get {
                return ResourceManager.GetString("TEXT_SAVE_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Diagram as an XML Workspace Document.
        /// </summary>
        internal static string TEXT_SAVE_DIAGRAM_AS_XML_WORKSPACE_DOCUMENT {
            get {
                return ResourceManager.GetString("TEXT_SAVE_DIAGRAM_AS_XML_WORKSPACE_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the diagram before closing?.
        /// </summary>
        internal static string TEXT_SAVE_DOCUMENT_BEFORE_CLOSING {
            get {
                return ResourceManager.GetString("TEXT_SAVE_DOCUMENT_BEFORE_CLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the current diagram before opening?.
        /// </summary>
        internal static string TEXT_SAVE_DOCUMENT_BEFORE_OPENING {
            get {
                return ResourceManager.GetString("TEXT_SAVE_DOCUMENT_BEFORE_OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save XML Workspace Document.
        /// </summary>
        internal static string TEXT_SAVE_XML_WORKSPACE_DOCUMENT {
            get {
                return ResourceManager.GetString("TEXT_SAVE_XML_WORKSPACE_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string TEXT_SCHEMA {
            get {
                return ResourceManager.GetString("TEXT_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Report.
        /// </summary>
        internal static string TEXT_SCHEMA_REPORT {
            get {
                return ResourceManager.GetString("TEXT_SCHEMA_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Schema Report.
        /// </summary>
        internal static string TEXT_SCHEMA_REPORT_ {
            get {
                return ResourceManager.GetString("TEXT_SCHEMA_REPORT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;SDE Connection.
        /// </summary>
        internal static string TEXT_SDE_CONNECTION_ {
            get {
                return ResourceManager.GetString("TEXT_SDE_CONNECTION_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;elect....
        /// </summary>
        internal static string TEXT_SELECT_ {
            get {
                return ResourceManager.GetString("TEXT_SELECT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select All.
        /// </summary>
        internal static string TEXT_SELECTALL_ {
            get {
                return ResourceManager.GetString("TEXT_SELECTALL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send &amp;Feedback.
        /// </summary>
        internal static string TEXT_SEND_FEEDBACK_ {
            get {
                return ResourceManager.GetString("TEXT_SEND_FEEDBACK_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Silver.
        /// </summary>
        internal static string TEXT_SILVER_ {
            get {
                return ResourceManager.GetString("TEXT_SILVER_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string TEXT_STANDARD {
            get {
                return ResourceManager.GetString("TEXT_STANDARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Standard.
        /// </summary>
        internal static string TEXT_STANDARD_ {
            get {
                return ResourceManager.GetString("TEXT_STANDARD_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Status Bar.
        /// </summary>
        internal static string TEXT_STATUSBAR_ {
            get {
                return ResourceManager.GetString("TEXT_STATUSBAR_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Windows....
        /// </summary>
        internal static string TEXT_TABWINDOWS_ {
            get {
                return ResourceManager.GetString("TEXT_TABWINDOWS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string TEXT_TEMPLATES {
            get {
                return ResourceManager.GetString("TEXT_TEMPLATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Toolbars.
        /// </summary>
        internal static string TEXT_TOOLBARS_ {
            get {
                return ResourceManager.GetString("TEXT_TOOLBARS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string TEXT_TOOLS_ {
            get {
                return ResourceManager.GetString("TEXT_TOOLS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        internal static string TEXT_TREE {
            get {
                return ResourceManager.GetString("TEXT_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tree.
        /// </summary>
        internal static string TEXT_TREE_ {
            get {
                return ResourceManager.GetString("TEXT_TREE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tutorials.
        /// </summary>
        internal static string TEXT_TUTORIALS_ {
            get {
                return ResourceManager.GetString("TEXT_TUTORIALS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TEXT_TYPE {
            get {
                return ResourceManager.GetString("TEXT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a question for help.
        /// </summary>
        internal static string TEXT_TYPE_A_QUESTION_FOR_HELP {
            get {
                return ResourceManager.GetString("TEXT_TYPE_A_QUESTION_FOR_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string TEXT_UNDO_ {
            get {
                return ResourceManager.GetString("TEXT_UNDO_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://maps.esri.com/diagrammer/createonetomanyrelationship.htm.
        /// </summary>
        internal static string TEXT_URL_ADDRELATIONSHIP {
            get {
                return ResourceManager.GetString("TEXT_URL_ADDRELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://maps.esri.com/diagrammer/addsubtype.htm.
        /// </summary>
        internal static string TEXT_URL_ADDSUBTYPE {
            get {
                return ResourceManager.GetString("TEXT_URL_ADDSUBTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ideas.arcgis.com.
        /// </summary>
        internal static string TEXT_URL_ARCGIS_IDEAS {
            get {
                return ResourceManager.GetString("TEXT_URL_ARCGIS_IDEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://kiwigis.blogspot.com/2009/08/how-to-create-data-report-with-arcgis.html.
        /// </summary>
        internal static string TEXT_URL_CREATE_DATA_REPORT {
            get {
                return ResourceManager.GetString("TEXT_URL_CREATE_DATA_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://maps.esri.com/diagrammer/createschemareport.htm.
        /// </summary>
        internal static string TEXT_URL_CREATE_SCHEMA_REPORT {
            get {
                return ResourceManager.GetString("TEXT_URL_CREATE_SCHEMA_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://forums.arcgis.com/forums/60-Data-Models.
        /// </summary>
        internal static string TEXT_URL_DISCUSSION {
            get {
                return ResourceManager.GetString("TEXT_URL_DISCUSSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.esri.com.
        /// </summary>
        internal static string TEXT_URL_ESRI_HOME {
            get {
                return ResourceManager.GetString("TEXT_URL_ESRI_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://arcscripts.esri.com/ContactAuthor.asp?dbid=15166.
        /// </summary>
        internal static string TEXT_URL_FEEDBACK {
            get {
                return ResourceManager.GetString("TEXT_URL_FEEDBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://maps.esri.com/diagrammer/history.txt.
        /// </summary>
        internal static string TEXT_URL_HISTORY {
            get {
                return ResourceManager.GetString("TEXT_URL_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://maps.esri.com/diagrammer/reorderfields.htm.
        /// </summary>
        internal static string TEXT_URL_REORDER_FIELDS {
            get {
                return ResourceManager.GetString("TEXT_URL_REORDER_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://maps.esri.com/diagrammer/userguide.pdf.
        /// </summary>
        internal static string TEXT_URL_USERGUIDE {
            get {
                return ResourceManager.GetString("TEXT_URL_USERGUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string TEXT_VERSION {
            get {
                return ResourceManager.GetString("TEXT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string TEXT_VIEW_ {
            get {
                return ResourceManager.GetString("TEXT_VIEW_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This work is protected by copyright law and international treaties. |Unauthorized reproduction or distribution of this program, or any portion of it, |may result in severe civil and criminal penalties, and will be prosecuted to the |maximum extent possible under the law..
        /// </summary>
        internal static string TEXT_WARNING_STATEMENT {
            get {
                return ResourceManager.GetString("TEXT_WARNING_STATEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Width.
        /// </summary>
        internal static string TEXT_WIDTH_ {
            get {
                return ResourceManager.GetString("TEXT_WIDTH_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string TEXT_WINDOW {
            get {
                return ResourceManager.GetString("TEXT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Window.
        /// </summary>
        internal static string TEXT_WINDOW_ {
            get {
                return ResourceManager.GetString("TEXT_WINDOW_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string TEXT_WINDOWS {
            get {
                return ResourceManager.GetString("TEXT_WINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Windows.
        /// </summary>
        internal static string TEXT_WINDOWS_ {
            get {
                return ResourceManager.GetString("TEXT_WINDOWS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml.
        /// </summary>
        internal static string TEXT_XML {
            get {
                return ResourceManager.GetString("TEXT_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Xml Report.
        /// </summary>
        internal static string TEXT_XML_REPORT_ {
            get {
                return ResourceManager.GetString("TEXT_XML_REPORT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Workspace Documents.
        /// </summary>
        internal static string TEXT_XML_WORKSPACE_DOCUMENT {
            get {
                return ResourceManager.GetString("TEXT_XML_WORKSPACE_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zoom.
        /// </summary>
        internal static string TEXT_ZOOM_ {
            get {
                return ResourceManager.GetString("TEXT_ZOOM_", resourceCulture);
            }
        }
    }
}
