//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.ArcGIS.Diagrammer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRI.ArcGIS.Diagrammer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ANNOTATION_FEATURE_CLASS {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ANNOTATION_FEATURE_CLASS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_APHABETICAL {
            get {
                object obj = ResourceManager.GetObject("BITMAP_APHABETICAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_CATALOG {
            get {
                object obj = ResourceManager.GetObject("BITMAP_CATALOG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_CATEGORIZED {
            get {
                object obj = ResourceManager.GetObject("BITMAP_CATEGORIZED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_CODED_VALUE_DOMAIN {
            get {
                object obj = ResourceManager.GetObject("BITMAP_CODED_VALUE_DOMAIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_DIMENSION_FEATURE_CLASS {
            get {
                object obj = ResourceManager.GetObject("BITMAP_DIMENSION_FEATURE_CLASS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ERRORS {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ERRORS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_ERRORS_ITEM {
            get {
                object obj = ResourceManager.GetObject("BITMAP_ERRORS_ITEM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_FEATURE_DATASET {
            get {
                object obj = ResourceManager.GetObject("BITMAP_FEATURE_DATASET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_FIELD {
            get {
                object obj = ResourceManager.GetObject("BITMAP_FIELD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_FOLDER_CLOSED {
            get {
                object obj = ResourceManager.GetObject("BITMAP_FOLDER_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_FOLDER_OPENED {
            get {
                object obj = ResourceManager.GetObject("BITMAP_FOLDER_OPENED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_GEODATABASE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_GEODATABASE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_GEOMETRIC_NETWORK {
            get {
                object obj = ResourceManager.GetObject("BITMAP_GEOMETRIC_NETWORK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_LINK {
            get {
                object obj = ResourceManager.GetObject("BITMAP_LINK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_MULTIPATCH_FEATURE_CLASS {
            get {
                object obj = ResourceManager.GetObject("BITMAP_MULTIPATCH_FEATURE_CLASS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_NETWORK_DATASET {
            get {
                object obj = ResourceManager.GetObject("BITMAP_NETWORK_DATASET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_POINT_FEATURE_CLASS {
            get {
                object obj = ResourceManager.GetObject("BITMAP_POINT_FEATURE_CLASS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_POLYGON_FEATURE_CLASS {
            get {
                object obj = ResourceManager.GetObject("BITMAP_POLYGON_FEATURE_CLASS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_POLYLINE_FEATURE_CLASS {
            get {
                object obj = ResourceManager.GetObject("BITMAP_POLYLINE_FEATURE_CLASS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_RANGE_DOMAIN {
            get {
                object obj = ResourceManager.GetObject("BITMAP_RANGE_DOMAIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_RASTER_BAND {
            get {
                object obj = ResourceManager.GetObject("BITMAP_RASTER_BAND", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_RASTER_CATALOG {
            get {
                object obj = ResourceManager.GetObject("BITMAP_RASTER_CATALOG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_RASTER_DATASET {
            get {
                object obj = ResourceManager.GetObject("BITMAP_RASTER_DATASET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_REFRESH {
            get {
                object obj = ResourceManager.GetObject("BITMAP_REFRESH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_RELATIONSHIP_CLASS {
            get {
                object obj = ResourceManager.GetObject("BITMAP_RELATIONSHIP_CLASS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_SUBTYPE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_SUBTYPE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_TABLE {
            get {
                object obj = ResourceManager.GetObject("BITMAP_TABLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_TERRAIN {
            get {
                object obj = ResourceManager.GetObject("BITMAP_TERRAIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_TOPOLOGY {
            get {
                object obj = ResourceManager.GetObject("BITMAP_TOPOLOGY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_WARNINGS {
            get {
                object obj = ResourceManager.GetObject("BITMAP_WARNINGS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BITMAP_WARNINGS_ITEM {
            get {
                object obj = ResourceManager.GetObject("BITMAP_WARNINGS_ITEM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;html&quot; doctype-public=&quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; doctype-system=&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot; /&gt;
        ///  &lt;xsl:param name=&quot;font&quot; select=&quot;font&quot; /&gt;
        ///  &lt;xsl:param name=&quot;backcolor&quot; select=&quot;backcolor&quot; /&gt;
        ///  &lt;xsl:param name=&quot;forecolor&quot; select=&quot;forecolor&quot; /&gt;
        ///  &lt;xsl:param name=&quot;size1&quot; select=&quot;size1&quot; /&gt;
        ///  &lt;xsl:param name=&quot;size2&quot; select=&quot;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_DATA_REPORT {
            get {
                return ResourceManager.GetString("FILE_DATA_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;
        ///      &lt;Domain xsi:type=&apos;esri:CodedValueDomain&apos;&gt;
        ///        &lt;DomainName&gt;Empty&lt;/DomainName&gt;
        ///        &lt;FieldType&gt;esriFieldTypeString&lt;/FieldType&gt;
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_DOMAIN_CODEDVALUE {
            get {
                return ResourceManager.GetString("FILE_DOMAIN_CODEDVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;
        ///      &lt;Domain xsi:type=&apos;esri:RangeDomain&apos;&gt;
        ///        &lt;DomainName&gt;Empty&lt;/DomainName&gt;
        ///        &lt;FieldType&gt;esriFieldTypeInteger&lt;/FieldType&gt;
        ///        &lt;Merg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_DOMAIN_RANGE {
            get {
                return ResourceManager.GetString("FILE_DOMAIN_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;
        ///      &lt;Domain xsi:type=&apos;esri:CodedValueDomain&apos;&gt;
        ///        &lt;DomainName&gt;AnnotationStatus&lt;/DomainName&gt;
        ///        &lt;FieldType&gt;esriFieldTypeSmallInteger&lt;/Fiel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_FEATURECLASS_ANNOTATION {
            get {
                return ResourceManager.GetString("FILE_FEATURECLASS_ANNOTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DEFeatureClass&apos;&gt;
        ///        &lt;CatalogPath&gt;/FC=Em [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_FEATURECLASS_DIMENSION {
            get {
                return ResourceManager.GetString("FILE_FEATURECLASS_DIMENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DEFeatureClass&apos;&gt;
        ///        &lt;CatalogPath&gt;/FC=Em [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_FEATURECLASS_MULTIPATCH {
            get {
                return ResourceManager.GetString("FILE_FEATURECLASS_MULTIPATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DEFeatureClass&apos;&gt;
        ///        &lt;CatalogPath&gt;/FC=Em [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_FEATURECLASS_POINT {
            get {
                return ResourceManager.GetString("FILE_FEATURECLASS_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DEFeatureClass&apos;&gt;
        ///        &lt;CatalogPath&gt;/FC=Em [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_FEATURECLASS_POLYGON {
            get {
                return ResourceManager.GetString("FILE_FEATURECLASS_POLYGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DEFeatureClass&apos;&gt;
        ///        &lt;CatalogPath&gt;/FC=Em [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_FEATURECLASS_POLYLINE {
            get {
                return ResourceManager.GetString("FILE_FEATURECLASS_POLYLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DEFeatureDataset&apos;&gt;
        ///        &lt;CatalogPath&gt;/FD= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_FEATUREDATASET {
            get {
                return ResourceManager.GetString("FILE_FEATUREDATASET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;xs:element name=&quot;UpdateGram&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Root element for delta geodatabase exchanges in xml&lt;/xs:documentation&gt;
        ///		&lt;/xs:annotation&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;xs:element name=&quot;GeodatabaseRelease&quot;&gt;
        ///					&lt;xs:complexType&gt;
        ///						&lt;xs:sequence&gt;
        ///							&lt;xs:element name=&quot;MajorVersion&quot; type=&quot;xs:int&quot;/&gt;
        ///							&lt;xs:element name=&quot;MinorVersion&quot; type=&quot;xs:int&quot;/&gt;
        ///							&lt;xs:e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_GEODATABASE_EXCHANGE {
            get {
                return ResourceManager.GetString("FILE_GEODATABASE_EXCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;
        ///      &lt;Domain xsi:type=&apos;esri:CodedValueDomain&apos;&gt;
        ///        &lt;DomainName&gt;EnabledDomain&lt;/DomainName&gt;
        ///        &lt;FieldType&gt;esriFieldTypeSmallInteger&lt;/FieldTy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_GEOMETRIC_NETWORK {
            get {
                return ResourceManager.GetString("FILE_GEOMETRIC_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DEFeatureDataset&apos;&gt;
        ///        &lt;CatalogPath&gt;/FD= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_NETWORK {
            get {
                return ResourceManager.GetString("FILE_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DERasterDataset&apos;&gt;
        ///        &lt;CatalogPath&gt;/RD=E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_RASTERBAND {
            get {
                return ResourceManager.GetString("FILE_RASTERBAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DERasterCatalog&apos;&gt;
        ///        &lt;CatalogPath&gt;/RCAT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_RASTERCATALOG {
            get {
                return ResourceManager.GetString("FILE_RASTERCATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DERasterDataset&apos;&gt;
        ///        &lt;CatalogPath&gt;/RD=E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_RASTERDATASET {
            get {
                return ResourceManager.GetString("FILE_RASTERDATASET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DETable&apos;&gt;
        ///        &lt;CatalogPath&gt;/OC=DestTable [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_RELATIONSHIPCLASS {
            get {
                return ResourceManager.GetString("FILE_RELATIONSHIPCLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot;
        ///	xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;xsl:output method=&quot;html&quot; doctype-public=&quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; doctype-system=&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot; /&gt;
        ///  &lt;xsl:param name=&quot;font&quot; select=&quot;font&quot; /&gt;
        ///  &lt;xsl:param name=&quot;backcolor&quot; select=&quot;backcolor&quot; /&gt;
        ///  &lt;xs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_SCHEMA_REPORT {
            get {
                return ResourceManager.GetString("FILE_SCHEMA_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DETable&apos;&gt;
        ///        &lt;CatalogPath&gt;/OC=Empty&lt;/Ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_SUBTYPE {
            get {
                return ResourceManager.GetString("FILE_SUBTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DETable&apos;&gt;
        ///        &lt;CatalogPath&gt;/OC=Empty&lt;/Ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_TABLE {
            get {
                return ResourceManager.GetString("FILE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/10.0&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DEFeatureDataset&apos;&gt;
        ///        &lt;CatalogPath&gt;/FD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_TERRAIN {
            get {
                return ResourceManager.GetString("FILE_TERRAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;esri:Workspace xmlns:esri=&apos;http://www.esri.com/schemas/ArcGIS/9.2&apos; xmlns:xsi=&apos;http://www.w3.org/2001/XMLSchema-instance&apos; xmlns:xs=&apos;http://www.w3.org/2001/XMLSchema&apos;&gt;
        ///  &lt;WorkspaceDefinition xsi:type=&apos;esri:WorkspaceDefinition&apos;&gt;
        ///    &lt;WorkspaceType&gt;esriLocalDatabaseWorkspace&lt;/WorkspaceType&gt;
        ///    &lt;Version&gt;&lt;/Version&gt;
        ///    &lt;Domains xsi:type=&apos;esri:ArrayOfDomain&apos;&gt;&lt;/Domains&gt;
        ///    &lt;DatasetDefinitions xsi:type=&apos;esri:ArrayOfDataElement&apos;&gt;
        ///      &lt;DataElement xsi:type=&apos;esri:DEFeatureDataset&apos;&gt;
        ///        &lt;CatalogPath&gt;/FD= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_TOPOLOGY {
            get {
                return ResourceManager.GetString("FILE_TOPOLOGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;html&quot; doctype-public=&quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; doctype-system=&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot; /&gt;
        ///  &lt;xsl:param name=&quot;font&quot; select=&quot;font&quot; /&gt;
        ///  &lt;xsl:param name=&quot;backcolor&quot; select=&quot;backcolor&quot; /&gt;
        ///  &lt;xsl:param name=&quot;forecolor&quot; select=&quot;forecolor&quot; /&gt;
        ///  &lt;xsl:param name=&quot;size1&quot; select=&quot;size1&quot; /&gt;
        ///  &lt;xsl:param name=&quot;size2&quot; select=&quot;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FILE_XML_REPORT {
            get {
                return ResourceManager.GetString("FILE_XML_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Coded Value.
        /// </summary>
        internal static string TEXT_ADD_CODED_VALUE {
            get {
                return ResourceManager.GetString("TEXT_ADD_CODED_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Coded Value Item.
        /// </summary>
        internal static string TEXT_ADD_CODED_VALUE_ITEM {
            get {
                return ResourceManager.GetString("TEXT_ADD_CODED_VALUE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Field.
        /// </summary>
        internal static string TEXT_ADD_FIELD {
            get {
                return ResourceManager.GetString("TEXT_ADD_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Index.
        /// </summary>
        internal static string TEXT_ADD_INDEX {
            get {
                return ResourceManager.GetString("TEXT_ADD_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Index Field.
        /// </summary>
        internal static string TEXT_ADD_INDEX_FIELD {
            get {
                return ResourceManager.GetString("TEXT_ADD_INDEX_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subtype Field.
        /// </summary>
        internal static string TEXT_ADD_SUBTYPE_FIELD {
            get {
                return ResourceManager.GetString("TEXT_ADD_SUBTYPE_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Indexes.
        /// </summary>
        internal static string TEXT_ADD_TO_INDEXES {
            get {
                return ResourceManager.GetString("TEXT_ADD_TO_INDEXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string TEXT_ALL_FILES {
            get {
                return ResourceManager.GetString("TEXT_ALL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical.
        /// </summary>
        internal static string TEXT_ALPHABETICAL {
            get {
                return ResourceManager.GetString("TEXT_ALPHABETICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation.
        /// </summary>
        internal static string TEXT_ANNOTATION {
            get {
                return ResourceManager.GetString("TEXT_ANNOTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A geodatabase feature class that stores text or graphics that provide information about features or general areas of a map (annotation).
        /// </summary>
        internal static string TEXT_ANNOTATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_ANNOTATION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Diagrammer.
        /// </summary>
        internal static string TEXT_APPLICATION {
            get {
                return ResourceManager.GetString("TEXT_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributed Relationship.
        /// </summary>
        internal static string TEXT_ATTRIBUTED_RELATIONSHIP {
            get {
                return ResourceManager.GetString("TEXT_ATTRIBUTED_RELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog View.
        /// </summary>
        internal static string TEXT_CATALOG_VIEW {
            get {
                return ResourceManager.GetString("TEXT_CATALOG_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorized.
        /// </summary>
        internal static string TEXT_CATEGORIZED {
            get {
                return ResourceManager.GetString("TEXT_CATEGORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Class).
        /// </summary>
        internal static string TEXT_CLASS_BR {
            get {
                return ResourceManager.GetString("TEXT_CLASS_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear.
        /// </summary>
        internal static string TEXT_CLEAR_ {
            get {
                return ResourceManager.GetString("TEXT_CLEAR_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear &amp;All.
        /// </summary>
        internal static string TEXT_CLEAR_ALL_ {
            get {
                return ResourceManager.GetString("TEXT_CLEAR_ALL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coded Value.
        /// </summary>
        internal static string TEXT_CODED_VALUE {
            get {
                return ResourceManager.GetString("TEXT_CODED_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type of attribute domain that defines a set of permissible values for an attribute in a geodatabase. A coded value domain consists of a code and its equivalent value.
        /// </summary>
        internal static string TEXT_CODED_VALUE_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_CODED_VALUE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coded Value Domain.
        /// </summary>
        internal static string TEXT_CODED_VALUE_DOMAIN {
            get {
                return ResourceManager.GetString("TEXT_CODED_VALUE_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex Edge.
        /// </summary>
        internal static string TEXT_COMPLEX_EDGE {
            get {
                return ResourceManager.GetString("TEXT_COMPLEX_EDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string TEXT_DATA {
            get {
                return ResourceManager.GetString("TEXT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Report.
        /// </summary>
        internal static string TEXT_DATA_REPORT {
            get {
                return ResourceManager.GetString("TEXT_DATA_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasets.
        /// </summary>
        internal static string TEXT_DATASETS {
            get {
                return ResourceManager.GetString("TEXT_DATASETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Default.
        /// </summary>
        internal static string TEXT_DEFAULT_ {
            get {
                return ResourceManager.GetString("TEXT_DEFAULT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Default).
        /// </summary>
        internal static string TEXT_DEFAULT_BR {
            get {
                return ResourceManager.GetString("TEXT_DEFAULT_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TEXT_DELETE {
            get {
                return ResourceManager.GetString("TEXT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Coded Value Item.
        /// </summary>
        internal static string TEXT_DELETE_CODED_VALUE_ITEM {
            get {
                return ResourceManager.GetString("TEXT_DELETE_CODED_VALUE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Field.
        /// </summary>
        internal static string TEXT_DELETE_FIELD {
            get {
                return ResourceManager.GetString("TEXT_DELETE_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Index.
        /// </summary>
        internal static string TEXT_DELETE_INDEX {
            get {
                return ResourceManager.GetString("TEXT_DELETE_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Index Field.
        /// </summary>
        internal static string TEXT_DELETE_INDEX_FIELD {
            get {
                return ResourceManager.GetString("TEXT_DELETE_INDEX_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Subtype Field.
        /// </summary>
        internal static string TEXT_DELETE_SUBTYPE_FIELD {
            get {
                return ResourceManager.GetString("TEXT_DELETE_SUBTYPE_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TEXT_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        internal static string TEXT_DIMENSION {
            get {
                return ResourceManager.GetString("TEXT_DIMENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A geodatabase feature class that stores dimension features.
        /// </summary>
        internal static string TEXT_DIMENSION_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_DIMENSION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string TEXT_DOMAIN {
            get {
                return ResourceManager.GetString("TEXT_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain View.
        /// </summary>
        internal static string TEXT_DOMAIN_VIEW {
            get {
                return ResourceManager.GetString("TEXT_DOMAIN_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        internal static string TEXT_DOMAINS {
            get {
                return ResourceManager.GetString("TEXT_DOMAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dropped object is not a geodatabase or SDE connection..
        /// </summary>
        internal static string TEXT_DROPPED_OBJECT_NOT_GEODATABASE {
            get {
                return ResourceManager.GetString("TEXT_DROPPED_OBJECT_NOT_GEODATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dropped object is not a valid geodatabase..
        /// </summary>
        internal static string TEXT_DROPPED_OBJECT_NOT_VALID_GEODATABASE {
            get {
                return ResourceManager.GetString("TEXT_DROPPED_OBJECT_NOT_VALID_GEODATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string TEXT_EMPTY {
            get {
                return ResourceManager.GetString("TEXT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string TEXT_ERRORS {
            get {
                return ResourceManager.GetString("TEXT_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Errors.
        /// </summary>
        internal static string TEXT_ERRORS_ {
            get {
                return ResourceManager.GetString("TEXT_ERRORS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Extent).
        /// </summary>
        internal static string TEXT_EXTENT_BR {
            get {
                return ResourceManager.GetString("TEXT_EXTENT_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Class.
        /// </summary>
        internal static string TEXT_FEATURE_CLASS {
            get {
                return ResourceManager.GetString("TEXT_FEATURE_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Dataset.
        /// </summary>
        internal static string TEXT_FEATURE_DATASET {
            get {
                return ResourceManager.GetString("TEXT_FEATURE_DATASET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of feature classes stored together that share the same spatial reference; that is, they share a coordinate system, and their features fall within a common geographic area.
        /// </summary>
        internal static string TEXT_FEATURE_DATASET_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_FEATURE_DATASET_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureClasses.
        /// </summary>
        internal static string TEXT_FEATURECLASSES {
            get {
                return ResourceManager.GetString("TEXT_FEATURECLASSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File Geodatabase.
        /// </summary>
        internal static string TEXT_FILE_GEODATABASE_ {
            get {
                return ResourceManager.GetString("TEXT_FILE_GEODATABASE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Flash.
        /// </summary>
        internal static string TEXT_FLASH_ {
            get {
                return ResourceManager.GetString("TEXT_FLASH_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Diagrammer could not export the geodatabase schema to XML because:.
        /// </summary>
        internal static string TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) An invalid network weight association, or.
        /// </summary>
        internal static string TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_1A {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) The connection to the ESRI OLE DB provider is invalid.
        /// </summary>
        internal static string TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_1B {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one or more datasets could not be found..
        /// </summary>
        internal static string TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_2 {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one or more tables could not be found..
        /// </summary>
        internal static string TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_3 {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a feature class&apos;s default subtype code cannot be retrieved or is invalid..
        /// </summary>
        internal static string TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_4 {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it could not instantiate an object class&apos; COM class extension..
        /// </summary>
        internal static string TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_5 {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the current user has insufficient permissions to access a dataset..
        /// </summary>
        internal static string TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_6 {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a table column is invalid or missing..
        /// </summary>
        internal static string TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_7 {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of an unknown or unspecified error. Please attempt exporting the geodatabase&apos;s.
        /// </summary>
        internal static string TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_8A {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_8A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schema to XML using ArcCatalog..
        /// </summary>
        internal static string TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_8B {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_8B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of an unknown or unspecified error. Please attempt exporting the geodatabase&apos;s.
        /// </summary>
        internal static string TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_9A {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_9A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schema to XML using ArcCatalog..
        /// </summary>
        internal static string TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_9B {
            get {
                return ResourceManager.GetString("TEXT_GEODATABASE_SCHEMA_EXPORT_FAILED_9B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric Network.
        /// </summary>
        internal static string TEXT_GEOMETRIC_NETWORK {
            get {
                return ResourceManager.GetString("TEXT_GEOMETRIC_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge and junction features that represent a linear network, such as a utility or hydrologic system, in which the connectivity of features is based on their geometric coincidence.
        /// </summary>
        internal static string TEXT_GEOMETRIC_NETWORK_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_GEOMETRIC_NETWORK_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Geometric Definition).
        /// </summary>
        internal static string TEXT_GEOMETRY_DEFINITION_BR {
            get {
                return ResourceManager.GetString("TEXT_GEOMETRY_DEFINITION_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Metadata).
        /// </summary>
        internal static string TEXT_METADATA_BR {
            get {
                return ResourceManager.GetString("TEXT_METADATA_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multipatch.
        /// </summary>
        internal static string TEXT_MULTIPATCH {
            get {
                return ResourceManager.GetString("TEXT_MULTIPATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type of geometry comprised of planar three-dimensional rings and triangles, used in combination to model objects that occupy discrete area or volume in three-dimensional space.
        /// </summary>
        internal static string TEXT_MULTIPATCH_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_MULTIPATCH_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string TEXT_NETWORK {
            get {
                return ResourceManager.GetString("TEXT_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of topologically connected network elements (edges, junctions, and turns) that are derived from network sources, typically used to represent a linear network, such as a road or subway system.
        /// </summary>
        internal static string TEXT_NETWORK_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_NETWORK_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Network Directions).
        /// </summary>
        internal static string TEXT_NETWORK_DIRECTIONS_BR {
            get {
                return ResourceManager.GetString("TEXT_NETWORK_DIRECTIONS_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have ArcGIS Desktop Installed.
        /// </summary>
        internal static string TEXT_NO_ARCGIS_DESKTOP {
            get {
                return ResourceManager.GetString("TEXT_NO_ARCGIS_DESKTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string TEXT_NONE_BR {
            get {
                return ResourceManager.GetString("TEXT_NONE_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not Available).
        /// </summary>
        internal static string TEXT_NOT_AVAILABLE_BR {
            get {
                return ResourceManager.GetString("TEXT_NOT_AVAILABLE_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Diagram.
        /// </summary>
        internal static string TEXT_OPEN_DIAGRAM {
            get {
                return ResourceManager.GetString("TEXT_OPEN_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Edge Edge Diagram.
        /// </summary>
        internal static string TEXT_OPEN_EDGE_EDGE_DIAGRAM {
            get {
                return ResourceManager.GetString("TEXT_OPEN_EDGE_EDGE_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Edge Junction Diagram.
        /// </summary>
        internal static string TEXT_OPEN_EDGE_JUNCTION_DIAGRAM {
            get {
                return ResourceManager.GetString("TEXT_OPEN_EDGE_JUNCTION_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Rule Diagram.
        /// </summary>
        internal static string TEXT_OPEN_RULE_DIAGRAM {
            get {
                return ResourceManager.GetString("TEXT_OPEN_RULE_DIAGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open XML Workspace Document.
        /// </summary>
        internal static string TEXT_OPEN_XML_WORKSPACE_DOCUMENT {
            get {
                return ResourceManager.GetString("TEXT_OPEN_XML_WORKSPACE_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string TEXT_OTHER {
            get {
                return ResourceManager.GetString("TEXT_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Personal Geodatabase.
        /// </summary>
        internal static string TEXT_PERSONAL_GEODATABASE_ {
            get {
                return ResourceManager.GetString("TEXT_PERSONAL_GEODATABASE_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string TEXT_POINT {
            get {
                return ResourceManager.GetString("TEXT_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Point).
        /// </summary>
        internal static string TEXT_POINT_BR {
            get {
                return ResourceManager.GetString("TEXT_POINT_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of geographic features with the point geometry, the same attributes, and the same spatial reference.
        /// </summary>
        internal static string TEXT_POINT_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_POINT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        internal static string TEXT_POLYGON {
            get {
                return ResourceManager.GetString("TEXT_POLYGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of geographic features with the polygon geometry, the same attributes, and the same spatial reference.
        /// </summary>
        internal static string TEXT_POLYGON_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_POLYGON_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline.
        /// </summary>
        internal static string TEXT_POLYLINE {
            get {
                return ResourceManager.GetString("TEXT_POLYLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of geographic features with the line geometry, the same attributes, and the same spatial reference.
        /// </summary>
        internal static string TEXT_POLYLINE_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_POLYLINE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string TEXT_RANGE {
            get {
                return ResourceManager.GetString("TEXT_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type of attribute domain that defines the range of permissible values for a numeric attribute.
        /// </summary>
        internal static string TEXT_RANGE_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_RANGE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Domain.
        /// </summary>
        internal static string TEXT_RANGE_DOMAIN {
            get {
                return ResourceManager.GetString("TEXT_RANGE_DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raster Band.
        /// </summary>
        internal static string TEXT_RASTER_BAND {
            get {
                return ResourceManager.GetString("TEXT_RASTER_BAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One layer in a raster dataset that represents data values for a specific range in the electromagnetic spectrum (such as ultraviolet, blue, green, red, and infrared), or radar, or other values derived by manipulating the original image bands..
        /// </summary>
        internal static string TEXT_RASTER_BAND_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_RASTER_BAND_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raster Catalog.
        /// </summary>
        internal static string TEXT_RASTER_CATALOG {
            get {
                return ResourceManager.GetString("TEXT_RASTER_CATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of raster datasets defined in a table of any format, in which the records define the individual raster datasets that are included in the catalog.
        /// </summary>
        internal static string TEXT_RASTER_CATALOG_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_RASTER_CATALOG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raster Dataset.
        /// </summary>
        internal static string TEXT_RASTER_DATASET {
            get {
                return ResourceManager.GetString("TEXT_RASTER_DATASET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A raster spatial data model that is stored in the geodatabase.
        /// </summary>
        internal static string TEXT_RASTER_DATASET_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_RASTER_DATASET_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Raster Definition).
        /// </summary>
        internal static string TEXT_RASTER_DEFINITION_BR {
            get {
                return ResourceManager.GetString("TEXT_RASTER_DEFINITION_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rasters.
        /// </summary>
        internal static string TEXT_RASTERS {
            get {
                return ResourceManager.GetString("TEXT_RASTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string TEXT_REFRESH {
            get {
                return ResourceManager.GetString("TEXT_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        internal static string TEXT_RELATIONSHIP {
            get {
                return ResourceManager.GetString("TEXT_RELATIONSHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item in the geodatabase that stores information about a relationship.
        /// </summary>
        internal static string TEXT_RELATIONSHIP_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_RELATIONSHIP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by The Applications Prototype Lab, ESRI Inc.
        /// </summary>
        internal static string TEXT_REPORT_CREDIT {
            get {
                return ResourceManager.GetString("TEXT_REPORT_CREDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Diagrammer is prototype application and is not supported by ESRI. The commands assoicated with this application and the output generated by those commands are not to be used in a production environment.
        /// ESRI is not reponsible for errors, ommission or any damages resulting from the use of application and associated output. Use of this application is
        /// conditional on the acceptance of this statement..
        /// </summary>
        internal static string TEXT_REPORT_DISCLAIMER {
            get {
                return ResourceManager.GetString("TEXT_REPORT_DISCLAIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Diagrammer.
        /// </summary>
        internal static string TEXT_REPORT_TITLE {
            get {
                return ResourceManager.GetString("TEXT_REPORT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string TEXT_SCHEMA {
            get {
                return ResourceManager.GetString("TEXT_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Report.
        /// </summary>
        internal static string TEXT_SCHEMA_REPORT {
            get {
                return ResourceManager.GetString("TEXT_SCHEMA_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema View.
        /// </summary>
        internal static string TEXT_SCHEMA_VIEW {
            get {
                return ResourceManager.GetString("TEXT_SCHEMA_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Scroll.
        /// </summary>
        internal static string TEXT_SCROLL_ {
            get {
                return ResourceManager.GetString("TEXT_SCROLL_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;SDE Connection.
        /// </summary>
        internal static string TEXT_SDE_CONNECTION_ {
            get {
                return ResourceManager.GetString("TEXT_SDE_CONNECTION_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string TEXT_SELECT {
            get {
                return ResourceManager.GetString("TEXT_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;elect.
        /// </summary>
        internal static string TEXT_SELECT_ {
            get {
                return ResourceManager.GetString("TEXT_SELECT_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;elect....
        /// </summary>
        internal static string TEXT_SELECT__ {
            get {
                return ResourceManager.GetString("TEXT_SELECT__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Existing Geodatabase.
        /// </summary>
        internal static string TEXT_SELECT_EXISTING_GEODATABASE {
            get {
                return ResourceManager.GetString("TEXT_SELECT_EXISTING_GEODATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set As Default.
        /// </summary>
        internal static string TEXT_SET_AS_DEFAULT {
            get {
                return ResourceManager.GetString("TEXT_SET_AS_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Edge.
        /// </summary>
        internal static string TEXT_SIMPLE_EDGE {
            get {
                return ResourceManager.GetString("TEXT_SIMPLE_EDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Junction.
        /// </summary>
        internal static string TEXT_SIMPLE_JUNCTION {
            get {
                return ResourceManager.GetString("TEXT_SIMPLE_JUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Spatial Reference).
        /// </summary>
        internal static string TEXT_SPATIAL_REFERENCE_BR {
            get {
                return ResourceManager.GetString("TEXT_SPATIAL_REFERENCE_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Storage Definition).
        /// </summary>
        internal static string TEXT_STORAGE_DEFINITION_BR {
            get {
                return ResourceManager.GetString("TEXT_STORAGE_DEFINITION_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtype.
        /// </summary>
        internal static string TEXT_SUBTYPE {
            get {
                return ResourceManager.GetString("TEXT_SUBTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A subset of features in a feature class or objects in a table that share the same attributes.
        /// </summary>
        internal static string TEXT_SUBTYPE_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_SUBTYPE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string TEXT_TABLE {
            get {
                return ResourceManager.GetString("TEXT_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A set of data elements arranged in rows and columns.
        /// </summary>
        internal static string TEXT_TABLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_TABLE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        internal static string TEXT_TERRAIN {
            get {
                return ResourceManager.GetString("TEXT_TERRAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A surface based on vector measurements stored in a geodatabase. Terrains live inside feature datasets and are comprised of one or more feature classes and rules..
        /// </summary>
        internal static string TEXT_TERRAIN_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_TERRAIN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Parse Failed.
        /// </summary>
        internal static string TEXT_TEXT_PARSE_FAILED {
            get {
                return ResourceManager.GetString("TEXT_TEXT_PARSE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topology.
        /// </summary>
        internal static string TEXT_TOPOLOGY {
            get {
                return ResourceManager.GetString("TEXT_TOPOLOGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arrangement that constrains how point, line, and polygon features share geometry.
        /// </summary>
        internal static string TEXT_TOPOLOGY_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_TOPOLOGY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string TEXT_UNTITLED {
            get {
                return ResourceManager.GetString("TEXT_UNTITLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string TEXT_VALIDATE {
            get {
                return ResourceManager.GetString("TEXT_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Validator.
        /// </summary>
        internal static string TEXT_VALIDATOR_ {
            get {
                return ResourceManager.GetString("TEXT_VALIDATOR_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Metadata.
        /// </summary>
        internal static string TEXT_VIEW_METADATA {
            get {
                return ResourceManager.GetString("TEXT_VIEW_METADATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        internal static string TEXT_WARNINGS {
            get {
                return ResourceManager.GetString("TEXT_WARNINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Warnings.
        /// </summary>
        internal static string TEXT_WARNINGS_ {
            get {
                return ResourceManager.GetString("TEXT_WARNINGS_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (WKT).
        /// </summary>
        internal static string TEXT_WKT_BR {
            get {
                return ResourceManager.GetString("TEXT_WKT_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Workspace).
        /// </summary>
        internal static string TEXT_WORKSPACE_BR {
            get {
                return ResourceManager.GetString("TEXT_WORKSPACE_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Workspace Document.
        /// </summary>
        internal static string TEXT_XML_WORKSPACE_DOCUMENT {
            get {
                return ResourceManager.GetString("TEXT_XML_WORKSPACE_DOCUMENT", resourceCulture);
            }
        }
    }
}
